language: ruby
script: bundle exec rake
cache:  bundler
sudo:   false

before_install: gem install bundler -v 1.17.3

rvm:
  - 2.6.2
  - 2.5.5
  - 2.4.5
  - 2.3.8
  - ruby-head
  # - jruby-9.2.3.0
  # - jruby-head

gemfile:
  - gemfiles/rails_60.gemfile
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_41.gemfile
  - gemfiles/rails_40.gemfile
  - gemfiles/rails_edge.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
    # - rvm: jruby-9.2.3.0
    # - rvm: jruby-head
    - gemfile: gemfiles/rails_edge.gemfile
    - gemfile: gemfiles/rails_41.gemfile
    - gemfile: gemfiles/rails_40.gemfile
  exclude:
    - rvm: ruby-head
      gemfile: gemfiles/rails_40.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_41.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_42.gemfile
    - rvm: 2.6.2
      gemfile: gemfiles/rails_50.gemfile
    - rvm: 2.6.2
      gemfile: gemfiles/rails_42.gemfile
    - rvm: 2.6.2
      gemfile: gemfiles/rails_41.gemfile
    - rvm: 2.6.2
      gemfile: gemfiles/rails_40.gemfile
    - rvm: 2.5.5
      gemfile: gemfiles/rails_50.gemfile
    - rvm: 2.5.5
      gemfile: gemfiles/rails_42.gemfile
    - rvm: 2.5.5
      gemfile: gemfiles/rails_41.gemfile
    - rvm: 2.5.5
      gemfile: gemfiles/rails_40.gemfile
    - rvm: 2.4.5
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.4.5
      gemfile: gemfiles/rails_60.gemfile
    - rvm: 2.4.5
      gemfile: gemfiles/rails_41.gemfile
    - rvm: 2.4.5
      gemfile: gemfiles/rails_40.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/rails_60.gemfile
