nguage: ruby
script: bundle exec rake
cache:  bundler
sudo:   false

before_install: gem install bundler -v 1.16.1

rvm:
  - 2.5.3
  - 2.4.5
  - 2.3.8
  - ruby-head
  # - jruby-9.2.3.0
  # - jruby-head

gemfile:
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_edge.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
    # - rvm: jruby-9.2.3.0
    # - rvm: jruby-head
    - gemfile: gemfiles/rails_edge.gemfile
  exclude:
    - rvm: 2.3.8
      gemfile: gemfiles/rails_edge.gemfile
